version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
      - redis
    container_name: go-app
    restart: on-failure

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    container_name: cassandra-db
    volumes:
      - ./schema.cql:/docker-entrypoint-initdb.d/schema.cql
   

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis-cache

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    container_name: nginx-proxy
    restart: on-failure
